### ISSUE TITLE
Laravel 5.0 support

### ISSUE THREAD

**Issue by slovenianGooner** [etrepat/baum#108]
Any chance of updating the required part of the composer.json so it can reflect on the new version of Laravel? Worked fine when it was 4.3, but now the name was changed to 5.0.

**Comment by ajtrichards** [comment]
I've added `"baum/baum" : "dev-develop"` to my composer and then added `'Baum\BaumServiceProvider',` to my `config/app.php` file and i'm getting an error:

`exception 'BadMethodCallException' with message 'Call to undefined method [package]'`

Any ideas?

**Comment by GrahamCampbell** [comment]
Fixed here: https://github.com/etrepat/baum/pull/139.
