### ISSUE TITLE
Call to undefined method Baum\Extensions\Query\Builder::sharedLock()

### ISSUE THREAD

**Issue by pckopat** [etrepat/baum#113]
```
BadMethodCallException
Call to undefined method Baum\Extensions\Query\Builder::sharedLock()
```

php ver: 5.5.11 
laravel ver: 4.0.0.0 
baum: 1.0.13

Model/Menu.php
```
use Baum\Node;
class Menu extends Node {
protected $table = 'menuler';
}
```

routes.php
```
Route::get('/', function()
{
    $root = Menu::create(['name' => 'Yazılım']);
    $php = Menu::create(['name' => 'PHP']); 
    $php->makeChildOf($root);
});
```
what I'm doing wrong?

**Comment by cristianszwarc** [comment]
Hi, do you remember when you added this changes? I may need to get an older stage. I'm stuck on 4.0 :(

**Comment by cristianszwarc** [comment]
removed a couple of lockForUpdate and the shared lock, so far so good

**Comment by etrepat** [comment]
Sorry for replying so late.

If stuck on 4.0, tagged release [1.0.12](https://github.com/etrepat/baum/tree/1.0.12) should be your best bet. If you've already solved it manually, no worries though.
