### ISSUE TITLE
how to import a csv file  and transfer it into a baum tree table

### ISSUE THREAD

**Issue by msrlinliu** [etrepat/baum#114]
I am loading the csv file into a table named as "node". Then query that"node" table to create a new baum-tree table "section". Basically, "node" table includes columns of "id", "organization_id", "parent_id", "entity_id", "entity_name", "active", "exclude_rollup". I hope can first scan out root nodes in "node" table and create corresponding root nodes in "sections" table; then scan "node" table line by line and create corresponding "section" nodes. At the same time, I find out parent section nodes in "section" table and use makeChildOf() function to setup their relationships.

here is the codes I used:
```
public function create()
	{
		DB::table('sections')->truncate();

		$rnodes = DB::table('nodes')->where('parent_id', '=', 0)->get();
		foreach ($rnodes as $rnode){
			//var_dump($rnode);
			$root = Section::create(['entity_id' => $rnode->entity_id, 'entity_name' => $rnode->entity_name, 'active' => $rnode->active, 'exclude_rollup' => $rnode->exclude_rollup, 'organization_id' => $rnode->organization_id]);
			$root->makeroot();
		}

		$nodes = DB::table('nodes')->where('parent_id', '!=', 0)->get();

		 foreach($nodes as $node){
		 	$section = Section::create(['entity_id' => $node->entity_id, 'entity_name' => $node->entity_name, 'active' => $node->active, 'exclude_rollup' => $node->exclude_rollup, 'organization_id' => $node->organization_id]);
		 	$parent_node = DB::table('nodes')->where('id', '=', $node->parent_id)->first();
		 	$parent_section = DB::table('sections')->where('entity_id', '=', $parent_node->entity_id)->first();
			$section->makeChildOf($parent_section);
		 }
	}
```
Everything is fine, except the last step, which is to run makeChildOf() function. It throws error:
```
Object of class stdClass could not be converted to string
```
Does I miss something?

**Comment by etrepat** [comment]
Sorry for the late reply.

What you ask is not supported by Baum but rather by Eloquent itself by chaining where calls:

``` php
Node::where('unique_id', '=', $unique_id)->where('name', '=', 'xxxx')->first();
```
