### ISSUE TITLE
validateBounds function ignores connection's table prefix

### ISSUE THREAD

**Issue by jecun** [etrepat/baum#120]
In the SetValidator Class the connection's table prefix is ignored. When validateBounds function is invoked it falis if your connection prefix is not empty.

I propose this: 
protected function validateBounds() {
    $connection = $this->node->getConnection();
    $grammar    = $connection->getQueryGrammar();

    $tableName      = $grammar->getTablePrefix().$this->node->getTable();

I already tried it and works flawlessly

**Comment by etrepat** [comment]
Sorry for getting back so late. This issue is already fixed in latest releases.

Thanks for reporting.
