### ISSUE TITLE
Display Categories in Hierarchy 

### ISSUE THREAD

**Issue by masterakado** [etrepat/baum#122]
Hello, I use this package for my laravel project to create parent and child categories, I can create parent/child categories but I can't seem to display them correctly in a hierarchy.
I use this function in my controller:
~~~
return View::make('categories.index') 
->with('categories', Category::all()->toHierarchy());
~~~
But It only returns the parent (root) categories in my view.
here is the view:
~~~
@foreach($categories as $category)
{{$category->name}}
@endforeach
~~~
I'm new to laravel and MVC architecture so any help will be appreciated. Thank you.

**Comment by etrepat** [comment]
Sorry for the late reply. 

I see you've managed to solve your problem, so I'll close this issue/question. 

As @ben-joostens explains, there's several ways (lots actually) to render a nested set structure. From another issue-comment we posted a [wiky entry](https://github.com/etrepat/baum/wiki/Example:-Presenting-a-hierarchy) regarding this as well.
