### ISSUE TITLE
Call to undefined method Baum\Extensions\Query\Builder::descendants()

### ISSUE THREAD

**Issue by diegotham** [etrepat/baum#127]
I get this error when I put this in my Controller:

```
	$carbrand = Category::where('name', '=', 'Cars')->descendants()->first();
```

I guess that's not the way, how could I do it?

Thank you

**Comment by etrepat** [comment]
The `descendants()` method is not a query scope. It belongs to a particular `Baum\Node` instance (and needs some of its values to perform the associated query).

Altering the order of the chained calls will, hopefully, accomplish what you intented:
```php
$carbrand = Category::where('name', '=', 'Cars')->first()->descendants();
```
Please note that this method will return a `Illuminate\Database\Eloquent\Builder` object for continued querying. If what you want is a `Collection` of the descedants you may just use the `getDescendants()` method:
```php
$carbrand = Category::where('name', '=', 'Cars')->first()->getDescendants();
```
