### ISSUE TITLE
Add table prefix 

### ISSUE THREAD

**Issue by konoff** [etrepat/baum#143]
In first place - I'm sorry for my terrible English. 
This commit add **Setting::get('connections.mysql.prefix')** to **$tableName** in **\Baum\SetValidator::validateBounds()**.

I'm sorry I didn't send any examples of code or debug information.
If it is strongly recommended - I'll try make some examples ASAP.

Thanks for your time.

5d167de911626c26e5b861d3e6dba3f7bbaf6bc1

**Comment by etrepat** [comment]
This is fixed now in master, 1.1.0 (L5), 1.0.15 (L4.2).

Thanks for reporting.
