### ISSUE TITLE
"Could not resolve target node" while creating root node

### ISSUE THREAD

**Issue by broszies** [etrepat/baum#144]
Hi,
I noticed this issue has come up before, so its most likely my fault and not Baums, but I would apprechiate the help.
One problem might be I do not fully understand the use of the protected $scoped . if I uncomment the line, the error is "Use of Undefined Constant - assumed id"

Also, if I try to edit a existing Category, I get a different error: "Value must be provided." 

Again, appologies, since I am relatively new to laravel (and obviously not a brilliant PHP programmer). if my errors are to basic to be resolved here, please let me know ;)

I will attach the Model, the form and the Controller. 

If someone could point me to a repository with a wrking Baum implementation, I would very much apprechiate it.

UPDATE: The category gets crated after the error, but the name does not get saved. The category then can be edited, updated and even its parent changed successfuly. I am at loss why the error shows up, though. Can it be related to using the translator?

My code:

// app/models/Category.php

use Vinkla\Translator\TranslatorTrait;
use Baum\Node;

class Category extends Node {

  use TranslatorTrait;
  /**
   * Table name.
   *
   * @var string
   */
  protected $table = 'categories';
  // *
  // * @var array
  // */
  protected $guarded = array('id', 'lft', 'rgt', 'depth');
  //  *
  //  * @var array
  //  */
  // protected $scoped = array(parent_id);

// All functions related to the Vinkla Translator
    
    // @var array
	  // MASS ASSIGNMENT -------------------------------------------------------
  	// define which attributes are mass assignable (for security)
  	// we only want these 3 attributes able to be filled
    
    protected $fillable = ['parent_id', 'name', 'description'];

    /**
     * @var string
     */
    protected $translator = 'CategoryTranslation';

    /**
     * @var array
     */
    protected $translatedAttributes = ['name', 'description'];

-------------------

create.blade.php

@extends('layouts.default')

@section('content')
    <div class="page-header">
        <h1><?php echo trans('categories.headline_create'); ?> <small><?php echo trans('categories.subline_create'); ?></small></h1>
    </div>
    <div class="form-group">
        <form action="{{ action('CategoriesController@store') }}" method="post" role="form">
            <label for="title"><?php echo trans('categories.parent'); ?></label>
            <input type="text" class="form-control" name="parent_id" />
            <label for="title"><?php echo trans('categories.name'); ?></label>
            <input type="text" class="form-control" name="name" />
            <label for="title"><?php echo trans('categories.description'); ?></label>
            <input type="text" class="form-control" name="description" />
        </div>
        <input type="submit" value="<?php echo trans('categories.create'); ?>" class="btn btn-primary" />
        <a href="{{ action('CategoriesController@index') }}" class="btn btn-link"><?php echo trans('categories.cancel'); ?></a>
    </form>
@stop

----------------------------------

<?php

class CategoriesController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	
  public function index()
    {
    // Show a listing of categories.
    $categories = Category::all();
    return View::make('categories.index', compact('categories'));
    }

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
    {
		//Show Create Categories Form
    return View::make('categories.create');
    }

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	   {
      //Store created unit in database
      $input = Input::all();
      $validation = Validator::make($input, Unit::$rules);
        if ($validation->passes())
            {
            Category::create($input);
            return Redirect::route('categories.index')
            ->with('message', trans('categories.success_create'));
            }
        return Redirect::route('categories.create')
            ->withInput()
            ->withErrors($validation)
            ->with('message', trans('validation.error'));
	   }
 

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
    $category = Category::find($id);
    if (is_null($category))
        {
        return Redirect::route('categories.index')
        ->with('message', 'Category not found');
        }
    return View::make('categories.edit', compact('category'));
  }

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
    public function update($id)
    {
      $input = Input::all();
      $validation = Validator::make($input, Category::$rules);
      if ($validation->passes())
          {
          $category = Category::find($id);
          $category->update($input);
          return Redirect::route('categories.index')
          ->with('message', trans('categories.success_update'));
          }
      return Redirect::route('categories.edit', $id)
      ->withInput()
      ->withErrors($validation)
      ->with('message', trans('validation.error'));
    }

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
    public function destroy($id)
    {
        Category::find($id)->delete();
        return Redirect::route('categories.index')
        ->with('message', trans('categories.success_delete'));
    }
}

**Comment by broszies** [comment]
Did a fresh install and tweaked some. A problem of integrating the vinkla translator, and not a problem of Baum, or so it seems for my untrained eye ;)

**Comment by illuminate3** [comment]
I'm having the issue of just getting the model to start ...

```

use Illuminate\Database\Eloquent\Model;

//use Laracasts\Presenter\PresentableTrait;
// use Vinkla\Translator\Translatable;
// use Vinkla\Translator\Contracts\Translatable as TranslatableContract;

use Baum\Node;
use Cache;

class Page extends Node {
//class Page extends Node implements TranslatableContract {

//  use Translatable;
//  use PresentableTrait;
```

I had to comment out the Translator package to use my model again.

Here's the error that I'm getting.

```
Page::__toString() must not throw an exception
```

Has anybody got Baum 1.\* to work with this package?

**Comment by atorscho** [comment]
Exactly same problem. No idea have to fix it, but cannot disable either of them either. :/
