### ISSUE TITLE
support for Laravel 5

### ISSUE THREAD

**Issue by nickbr5** [etrepat/baum#153]
Hi,

would it be possible to upgrade this package to work on L5?
Or does anybody know a way to get this package working on L5?

thanks

**Comment by Pedramrn** [comment]
I've test it a couple days ago and it worked without any issues.

**Comment by nickbr5** [comment]
I get the message "Call to undefined method [package]". I've read that most of the packages have this after switching to L5.
Did you do something to solve this in general?

**Comment by etrepat** [comment]
I've just pushed an update for it to work with L5. Please use the 1.1.0 tagged release.

Feel free to report any issues you may encounter.

Thanks.
