### ISSUE TITLE
Change key from response and convert to array rather than nested object

### ISSUE THREAD

**Issue by andyjessop** [etrepat/baum#158]
I've got a collection `$tree` that is being converted to json with `Response::json()`. The key is being automatically set to the `id` of the first object. Is there a way to remove this, or restructure.

Code: 

```
$tree = $post->getDescendantsAndSelf()->toHierarchy();
return Response::json($tree);
```

It is currently responding with:

```
{"1":{"id":"1","parent_id":null,"lft":"1","rgt":"8","depth":"0"...
```

When I want is:

```
{'data':[{"id":"1","parent_id":null,"lft":"1","rgt":"8","depth":"0"...
```

**Comment by etrepat** [comment]
The `toHierarchy` method returns a nested object as the keys for the internal node array are its primary keys (it is in fact a dictionary).

What you need should be easily solved by using `values()` on the resulting `Illuminate\Support\Collection` object (http://laravel.com/api/5.0/Illuminate/Support/Collection.html#method_values). 

So, following your example:

``` php
$tree = $post->getDescendantsAndSelf()->toHierarchy();
return Response::json($tree->values());
```

will get you:  `[{"id":"1","parent_id":null,"lft":"1","rgt":"8","depth":"0"...`. Then, to get the structure you need/expect, you can do something like:

``` php
$tree = $post->getDescendantsAndSelf()->toHierarchy();
$response = array('data' => $tree->values());
return Response::json($response);
```

Hope it helps.
