### ISSUE TITLE
Question: How to make an existing record a node

### ISSUE THREAD

**Issue by lriggle-strib** [etrepat/baum#177]
I'm looking at applying a nested set structure to an already existing data set and I was wondering how to use your tool to update existing records to make them nodes. All I'm seeing in the documentation is how to create new nodes, not adding a node from an existing record.

**Comment by andreshg112** [comment]
Hi, @lriggle-strib! Did you find a solution? I'm trying to do the same because It triggers an error.
https://github.com/etrepat/baum/issues/294

**Comment by lriggle-strib** [comment]
@andreshg112 Honestly, I don't remember. I don't think I did and switched to using a different package.

**Comment by andreshg112** [comment]
@lriggle-strib , maybe this https://github.com/lazychaser/laravel-nestedset?

**Comment by andreshg112** [comment]
Yes, this package has a related function.
https://github.com/lazychaser/laravel-nestedset#migrating-from-basic-parentage-info
