### ISSUE TITLE
Incorrect left and right value when adding new node.

### ISSUE THREAD

**Issue by bczm8703** [etrepat/baum#178]
hi.
i am using Laravel 5.1 and Baum ver 1.1.1.

when i tried to add a new node to be under a existing node in my tree, the parent_id is correct but the re calculated left and right value for the new node is incorrect. 
please see attached image

table schema:
![screen shot 2015-09-01 at 4 55 42 pm](https://cloud.githubusercontent.com/assets/8233066/9599974/9271aeb4-50ca-11e5-87ac-97441807619b.png)

data before adding new node
![screen shot 2015-09-01 at 4 58 13 pm](https://cloud.githubusercontent.com/assets/8233066/9600069/671bfcd2-50cb-11e5-8b51-6813e933f54b.png)

data after adding node
![screen shot 2015-09-01 at 4 58 36 pm](https://cloud.githubusercontent.com/assets/8233066/9600077/789aae18-50cb-11e5-8e56-0aa24e52b4c2.png)

expected result 
![screen shot 2015-09-01 at 5 02 48 pm](https://cloud.githubusercontent.com/assets/8233066/9600087/81c77f16-50cb-11e5-92cd-f74e79856903.png)

**Comment by bczm8703** [comment]
sorry... my bad... it appears to be my error

**Comment by bbuie** [comment]
@bczm8703 What was the error? I seem to be getting it too.
