### ISSUE TITLE
Build Tree Issue

### ISSUE THREAD

**Issue by abbu1534** [etrepat/baum#209]
Hi, I am using mysql database
When i use buildTree() function in my application it gives already begin transaction exception.
Mysql exception like 
 General error: 2030 This command is not supported in the prepared statement protocol yet
Can you give a solution for this. Thank you.

**Comment by markvaneijk** [comment]
What MySQL version are you using?

**Comment by abbu1534** [comment]
I am using mysql 5.6.27 version on  ubuntu 15.10 and using laravel 5.1 framework

**Comment by abbu1534** [comment]
Is there any body?
