### ISSUE TITLE
Building/Rebuilding tree within given scope

### ISSUE THREAD

**Issue by salehliam** [etrepat/baum#245]
Hello Guys,

I'm trying to figure out how to build/rebuild tree using given nodes collection and within a given scope. 
No success. Any suggestion? 

My model extending Baum\Node class has the following property declared 

`protected $scoped  =  array('firm_id');`

And firm_id saves into database properly. Everytime I serialize my structure from the view and pass it to the build method I wish only nodes with given 'firm_id' were processed and the others remained intact. 

Thanks in advance!

**Comment by Machecek** [comment]
Did you find any solution to this? @salehliam
