### ISSUE TITLE
Why are lft/rgt/depth always null?

### ISSUE THREAD

**Issue by fzyzcjy** [etrepat/baum#260]
When I use `create` or other methods, the lft/rgt/depth of the newly created node is always null, but the parent_id and so on are very normal. Then if I use  `getDescendantsAndSelf` and so on, I will get an exception because of the null columns.
Only if I use `rebuild()` will all the nodes have not-null normal values. But then if I `create()` a new node the columns of it are still null.
Looking forward to your reply!

**Comment by fzyzcjy** [comment]
Any help?? Thanks!!

**Comment by egitimplus** [comment]
i have same problem

**Comment by fzyzcjy** [comment]
@egitimplus have you solved it

**Comment by egitimplus** [comment]
@turtlegood not yet. this problem is new for me. i didnt see it before. i think some packages has cause that.

For now, i call manually rebuild() if lft / right/ depth is null.

**Comment by fzyzcjy** [comment]
Finally I used another library: [laravel-nestedset](https://github.com/lazychaser/laravel-nestedset) and it works well.
By the way, baum has another issue: there will be deadlocks sometimes.
