### ISSUE TITLE
Call to undefined method Illuminate\Events\Dispatcher::fire() in Laravel 5.8

### ISSUE THREAD

**Issue by kheengz** [etrepat/baum#307]
the `fire` method has been changed to `dispatch` here https://laravel.com/docs/5.8/upgrade#events in laravel new upgrade.
@etrepat

**Comment by weboAp** [comment]
@kheengz check the branch:v2.x-dev 

```
  /**
   * Fire the given move event for the model.
   *
   * @param  string $event
   * @param  bool   $halt
   * @return mixed
   */
  protected function fireMoveEvent($event, $halt = true) {
    if ( !isset(static::$dispatcher) ) return true;
    // Basically the same as \Illuminate\Database\Eloquent\Model->fireModelEvent
    // but we relay the event into the node instance.
    $event = "eloquent.{$event}: ".get_class($this->node);
    $method = $halt ? 'until' : 'dispatch';
    return static::$dispatcher->$method($event, $this->node);
  }
```

**Comment by kheengz** [comment]
Yeah version `v2.x-dev` fixes it.

**Comment by zahirzohair** [comment]
i have exactly the same issue. i tried "buam/buam" : "2.x-dev" but didnt work for me. any other solution ?

**Comment by kheengz** [comment]
@zahirzohair are you on **laravel 5.8**? 

What specific error are you having?

**Comment by Nivekiba** [comment]
> Yeah version `v2.x-dev` fixes it.

what should i do if i want to install this version of baum in my laravel project ?

**Comment by cp-vrkansagara** [comment]
> > Yeah version `v2.x-dev` fixes it.
> 
> what should i do if i want to install this version of baum in my laravel project ?

composer require "baum/baum:v2.x-dev"
