### ISSUE TITLE
Order by on Immediate Descendants (tested case)

### ISSUE THREAD

**Issue by kJamesy** [etrepat/baum#55]
This: 
$immediateDescendants = static::where('parent_id', $root->id)->orderBy('order')->get();

And
$immediateDescendants = $root->immediateDescendants()->orderBy('order')->get();

Return the same results but the second case does not obey the 'order'. Is this the intended behaviour?

**Comment by vrgenl** [comment]
Maybe put this on the readme.md as it's quite a usefull method :)
