### ISSUE TITLE
Create Headers from XML

### ISSUE THREAD

**Issue by maximerassi** [etrepat/baum#80]
We needed this functionality so we put together something quick down below.
If it can be useful to anyone else or if you have any suggestions for improvement, here it is.

https://gist.github.com/garagesocial/32334d9af04dfc0112fd

```
<?    
 
  $data = '
    <header name="A" slug="a">
      <header name="B" slug="b">
 
        <header name="C" slug="c">
          <header name="D" slug="d" />
        </header>
 
      </header>
    </header>
  ';
 
  $this->hfxParseContent($data);
```

**Comment by etrepat** [comment]
I've put a link to your gist in the project wiki. Thank you very much.
