### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by axuscreative** [etrepat/baum#83]
Is there anyway to paginate the the hierarchy tree? I have a hack job right now but wanted to know if there was a way to use Laravel's Paginate().

**Comment by efst** [comment]
I am having the same issue, my code is:

$categories = CategoryProvider::createModel();
$categories= $categories->getNestedList('name', 'id','-');	
$categories = $categories->paginate(5);

And the error that I get is:
Call to a member function paginate() on array

My table looks like:

Fruits
---Apple
---Mango
Vegetables
---Potato
---Tomato
--- XYZ
Root Cat 3
Root Cat 4
Root Cat 5

**Comment by VitoScaletta** [comment]
Hello!

I have here is such a request:

$portfolio = Portfolio::select([ 'mg_portfolio.id', 'mg_portfolio.parent_id', 'mg_portfolio.lft', 'mg_portfolio.rgt', 'mg_portfolio.depth', 'mg_portfolio.slug', 'mg_portfolio.image', 'mg_portfolio_body.name', 'mg_portfolio_body.site_type'  ])
                              ->join('mg_portfolio_body', 'mg_portfolio_body.portfolio_id', '=', 'mg_portfolio.id')
                              ->where('mg_portfolio_body.lang', '=', App::getLocale())
                              ->paginate(9);

How do I apply the method "->toHierarchy()"???

Thanks in advance for your reply.
