### ISSUE TITLE
buildTree - order by json key, not ID

### ISSUE THREAD

**Issue by aureliusm** [etrepat/baum#98]
Hi,

I'm having an issue where I'm sending a "angular ui tree" json structure and pass it to buildTree method. 

Problem is that the order is not necessarily the same as page id, but buildTree is ordering not by json key's but by id and so nothing is changed.

Example json where ITEM 1 should be above ITEM 2, but it's not:

``` json
[
    {
        "id": 1,
        "parent_id": null,
        "title": "Menu root",
        "children": [
            {
                "id": 4,
                "parent_id": 1,
                "title": "item 1",
                "children": []
            },
            {
                "id": 3,
                "parent_id": 1,
                "title": "item 2",
                "children": []
            }
        ]
    }
]
```

Many thanks for your help and a great plugin!

**Comment by imade-nl** [comment]
I ran into the same problem. The buildTree method saves the hierarchy, but not the correct order.
I use the jquery plugin [nestedSortable](http://mjsarfatti.com/sandbox/nestedSortable/) toHierarchy method to generate an array with the new hierarchy.
